// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/wallet/v1/wallet.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateAddressRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAddressRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAddressRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAddressRequestMultiError, or nil if none found.
func (m *CreateAddressRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAddressRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := CreateAddressRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateAddressRequestMultiError(errors)
	}

	return nil
}

// CreateAddressRequestMultiError is an error wrapping multiple validation
// errors returned by CreateAddressRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateAddressRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAddressRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAddressRequestMultiError) AllErrors() []error { return m }

// CreateAddressRequestValidationError is the validation error returned by
// CreateAddressRequest.Validate if the designated constraints aren't met.
type CreateAddressRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAddressRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAddressRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAddressRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAddressRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAddressRequestValidationError) ErrorName() string {
	return "CreateAddressRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAddressRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAddressRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAddressRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAddressRequestValidationError{}

// Validate checks the field values on CreateAddressResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAddressResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAddressResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAddressResponseMultiError, or nil if none found.
func (m *CreateAddressResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAddressResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	if len(errors) > 0 {
		return CreateAddressResponseMultiError(errors)
	}

	return nil
}

// CreateAddressResponseMultiError is an error wrapping multiple validation
// errors returned by CreateAddressResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateAddressResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAddressResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAddressResponseMultiError) AllErrors() []error { return m }

// CreateAddressResponseValidationError is the validation error returned by
// CreateAddressResponse.Validate if the designated constraints aren't met.
type CreateAddressResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAddressResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAddressResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAddressResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAddressResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAddressResponseValidationError) ErrorName() string {
	return "CreateAddressResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAddressResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAddressResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAddressResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAddressResponseValidationError{}

// Validate checks the field values on TransferRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TransferRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransferRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransferRequestMultiError, or nil if none found.
func (m *TransferRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TransferRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetToken()) < 1 {
		err := TransferRequestValidationError{
			field:  "Token",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDstAddress()) < 1 {
		err := TransferRequestValidationError{
			field:  "DstAddress",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := TransferRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := TransferRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TransferRequestMultiError(errors)
	}

	return nil
}

// TransferRequestMultiError is an error wrapping multiple validation errors
// returned by TransferRequest.ValidateAll() if the designated constraints
// aren't met.
type TransferRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransferRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransferRequestMultiError) AllErrors() []error { return m }

// TransferRequestValidationError is the validation error returned by
// TransferRequest.Validate if the designated constraints aren't met.
type TransferRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransferRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransferRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransferRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransferRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransferRequestValidationError) ErrorName() string { return "TransferRequestValidationError" }

// Error satisfies the builtin error interface
func (e TransferRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransferRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransferRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransferRequestValidationError{}

// Validate checks the field values on TransferResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TransferResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransferResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransferResponseMultiError, or nil if none found.
func (m *TransferResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TransferResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Hash

	if len(errors) > 0 {
		return TransferResponseMultiError(errors)
	}

	return nil
}

// TransferResponseMultiError is an error wrapping multiple validation errors
// returned by TransferResponse.ValidateAll() if the designated constraints
// aren't met.
type TransferResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransferResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransferResponseMultiError) AllErrors() []error { return m }

// TransferResponseValidationError is the validation error returned by
// TransferResponse.Validate if the designated constraints aren't met.
type TransferResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransferResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransferResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransferResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransferResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransferResponseValidationError) ErrorName() string { return "TransferResponseValidationError" }

// Error satisfies the builtin error interface
func (e TransferResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransferResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransferResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransferResponseValidationError{}

// Validate checks the field values on TransferCallback with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TransferCallback) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransferCallback with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransferCallbackMultiError, or nil if none found.
func (m *TransferCallback) ValidateAll() error {
	return m.validate(true)
}

func (m *TransferCallback) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for Hash

	if len(errors) > 0 {
		return TransferCallbackMultiError(errors)
	}

	return nil
}

// TransferCallbackMultiError is an error wrapping multiple validation errors
// returned by TransferCallback.ValidateAll() if the designated constraints
// aren't met.
type TransferCallbackMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransferCallbackMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransferCallbackMultiError) AllErrors() []error { return m }

// TransferCallbackValidationError is the validation error returned by
// TransferCallback.Validate if the designated constraints aren't met.
type TransferCallbackValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransferCallbackValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransferCallbackValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransferCallbackValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransferCallbackValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransferCallbackValidationError) ErrorName() string { return "TransferCallbackValidationError" }

// Error satisfies the builtin error interface
func (e TransferCallbackValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransferCallback.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransferCallbackValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransferCallbackValidationError{}

// Validate checks the field values on DepositCallback with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DepositCallback) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DepositCallback with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DepositCallbackMultiError, or nil if none found.
func (m *DepositCallback) ValidateAll() error {
	return m.validate(true)
}

func (m *DepositCallback) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for Address

	// no validation rules for Amount

	// no validation rules for Hash

	if len(errors) > 0 {
		return DepositCallbackMultiError(errors)
	}

	return nil
}

// DepositCallbackMultiError is an error wrapping multiple validation errors
// returned by DepositCallback.ValidateAll() if the designated constraints
// aren't met.
type DepositCallbackMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DepositCallbackMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DepositCallbackMultiError) AllErrors() []error { return m }

// DepositCallbackValidationError is the validation error returned by
// DepositCallback.Validate if the designated constraints aren't met.
type DepositCallbackValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DepositCallbackValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DepositCallbackValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DepositCallbackValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DepositCallbackValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DepositCallbackValidationError) ErrorName() string { return "DepositCallbackValidationError" }

// Error satisfies the builtin error interface
func (e DepositCallbackValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDepositCallback.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DepositCallbackValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DepositCallbackValidationError{}
